#
name: Private Repo Push

# Configures this workflow to run every time a change is pushed to the branch called `main`. And to build on a schedule.
on:
  push:
    branches: ['main']
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 1"

env: 
  IMAGE_NAME: datawave-stack
  JAVA_VERSION: '11'
  JAVA_DISTRIBUTION: 'zulu' #This is the default on v1 of the action for 1.8

jobs:
  build-and-push-self-hosted-images:
    runs-on: self-hosted
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      #
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ vars.SELF_HOSTED_REGISTRY_ROOT }}
          username: ${{ secrets.CY_ROBOT_ACCOUNT_USER }}
          password: ${{ secrets.CY_ROBOT_ACCOUNT_SECRET }}
      - name: Extract metadata (tags, labels) for Docker for base image
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: "${{ vars.SELF_HOSTED_REGISTRY }}/${{ env.IMAGE_NAME }}"
      # This step uses the `docker/build-push-action` action to build the image, based on your repository's `Dockerfile`. If the build succeeds, it pushes the image to the registy in the SELF_HOSTED_REGISTRY variable.
      # It uses the `context` parameter to define the build's context as the set of files located in the specified path. For more information, see "[Usage](https://github.com/docker/build-push-action#usage)" in the README of the `docker/build-push-action` repository.
      # It uses the `tags` and `labels` parameters to tag and label the image with the output from the "meta" step.
      - name: Build and push Docker base image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: datawave-base/
          push: true
          tags: "${{ vars.SELF_HOSTED_REGISTRY }}/${{ env.IMAGE_NAME }}-base:${{ github.ref_name  }}"
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            # Map a GitHub env var to a Docker build arg
            REGISTRY=${{ vars.SELF_HOSTED_REGISTRY }}
      - name: Generate artifactory.repo file
        env:
          # Replace ARTIFACTORY_TOKEN with your real secret name in GitHub Settings > Secrets and variables > Actions
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
        run: |
          cat > datawave-hadoop/artifactory.repo <<EOF
          [Artifactory]
          name=Artifactory
          baseurl=https://datawave-token:${ARTIFACTORY_TOKEN}@artifactory.adv.evoforge.org/artifactory/dwp-rpm-local/el8/
          enabled=1
          gpgcheck=0
          sslverify=0
          EOF
      - name: Build and push Docker hadoop image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: datawave-hadoop/
          push: false
          load: true
          tags: "${{ vars.SELF_HOSTED_REGISTRY }}/${{ env.IMAGE_NAME }}-hadoop:${{ github.ref_name  }}"
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            # Map a GitHub env var to a Docker build arg
            REGISTRY=${{ vars.SELF_HOSTED_REGISTRY }}
      - name: Build and push Docker accumulo image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: datawave-accumulo/
          push: false
          tags: "${{ vars.SELF_HOSTED_REGISTRY }}/${{ env.IMAGE_NAME }}-accumulo:${{ github.ref_name  }}"
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            # Map a GitHub env var to a Docker build arg
            REGISTRY=${{ vars.SELF_HOSTED_REGISTRY }}